### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by aadium** [subinoybiswas/nimbus-frontend#2]
![image](https://github.com/user-attachments/assets/30570af5-393b-4227-a7f9-7ba0de78fabd)

**Comment by aadium** [comment]
This is what happens when I try to view an uploaded image

**Comment by subinoybiswas** [comment]
Thanks for bringing this to my attention, there was a issue with uploading. It's fixed now please try it out

**Comment by aadium** [comment]
It works now
